services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123456}
      POSTGRES_DB: ${POSTGRES_DB:-postgres_db}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data}
    volumes:
      - postgres_data:${PGDATA:-/var/lib/postgresql/data}
      - ./init-scripts:/docker-entrypoint-initdb.d
    ports:
      - '${DB_PORT:-5432}:5432'
    networks:
      - postgres_network
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4:7.6
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@admin.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-qwerty}
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    ports:
      - '${PGADMIN_PORT:-5050}:80'
    networks:
      - postgres_network
    depends_on:
      - postgres
    restart: unless-stopped

networks:
  postgres_network:

volumes:
  postgres_data:
  pgadmin_data:
